// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnlWb58Dz8lF1-cqOydEBjDOJ3-cxoRb0',
    appId: '1:360907017576:web:ae566f606e5521ad179add',
    messagingSenderId: '360907017576',
    projectId: 'mess-managemnt-7b196',
    authDomain: 'mess-managemnt-7b196.firebaseapp.com',
    storageBucket: 'mess-managemnt-7b196.firebasestorage.app',
    measurementId: 'G-M8YTHN8GVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw80rBxCIHlMhHu4mpwkVB9GSlz1aE6Q8',
    appId: '1:360907017576:android:43a3adcd752f575b179add',
    messagingSenderId: '360907017576',
    projectId: 'mess-managemnt-7b196',
    storageBucket: 'mess-managemnt-7b196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ljCvXLK_15cfeCfk5TaN9tM6Ciwpq0g',
    appId: '1:360907017576:ios:abeb52185225234d179add',
    messagingSenderId: '360907017576',
    projectId: 'mess-managemnt-7b196',
    storageBucket: 'mess-managemnt-7b196.firebasestorage.app',
    iosBundleId: 'com.example.messManagement',
  );
}




